org: hugoforte
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  goodbye:
    handler: handler.goodbye
    events:
      - httpApi:
          path: /
          method: get
